### ISSUE TITLE
Thor needs a pre-authenticated landing page

### ISSUE THREAD

**Issue by albertwu** [ucla/logon#6]
or better stated: we need to take a fresh look at the overall navigation/user experience for Thor:
- When a user visits the site without any other context, what are the most likely actions s/he would want to take?
1. Create a UCLA Logon ID?
2. Look Up My UCLA Logon ID?
3. Reset Forgotten Password?
4. Manage My UCLA Logon Profile (view profile, change security setting - change password, change challenge question, change MFA settings)
5. Get Help for My UCLA Logon ID?

What is the best way to present those options to a person in the most intuitive manner? Embedding key actions within body text is not likely effective.  People don't read. 

Perhaps a variant of https://myaccount.google.com is a good place to start.

**Comment by erutan** [comment]
1) Do you have any data/metrics? It's one thing that's consistently lacking when asking questions like these, otherwise it's a toss between following previous directions or assuming new ones.

2) The "manage" section follows a similar idea to the google template mentioned. Given that (which was a late addition) is there it'd make sense to match the non logged in stuff to that as well.

Modernizing the landing page seems something good to do for 1.0. Now that things have been expanded out to their more traditional structure it's more important than it was in previous designs, and it wasn't something all that much time has been spent on (and doesn't impact overall architecture).
