### ISSUE TITLE
fine tuning Thor UI design "feel" - we need to shift either much closer to SSO or much closer to IT

### ISSUE THREAD

**Issue by albertwu** [ucla/logon#7]
As I look at the current design, I think we need to commit to shifting to align with either of the two designs, not hover in the middle. 

Personally, I am leaning toward aligning closer with SSO with the following tweaks:
1. Instead of thinking of the cloud image as background for the header, use it as background on the desktop
2. Header has transparent background, therefore the background image shows
3. Use the footer design from the SSO (will need to figure out how it flows from the content area
4. Place content page with the current implied width, which for the most part, will fill the width of the browser window. However, if a user sets the browser wide enough, the background appears on left and right.
5. Where applicable, apply layout templates (will likely need minor adjustments) from http://uclait.rollingorange.com/visual-design-r4/templates.php to create structure. For example, the 3-column stack is analogous to https://myaccount.google.com, while the Service: Detail template can be useful when rendering the pages within https://myaccount.google.com/privacy#personalinfo + more
6. Keep the IT site typography and button design, which means we'll at some point, perhaps this release, retrofit SSO to match.

**Comment by erutan** [comment]
re: 1-4, if we're only showing the clouds background to the left and right of content pages at wide resolutions (and the rest is behind transparent backgrounds) i'm not sure how much of a tie in that is. It'd be fairly easy to do, but it only really ties on mobile (header) and wide desktop displays. I'd also assume a drop back to white as the background color for the content area. I like this better from an aesthetic standpoint, but it'll be interesting how it ties things.

5, Service detail doesn't seem appropriate for the managed pages because the right column is (across all RO templates) used for secondary/tertiary information (with the possible exception being anchor links in the article page, but it's a bit unqiue) not primary navigation within a related set of pages. What we'd normally call primary navigation occurs in a column on the left, as seen in the basic content pages (which I loosely borrowed visual styling from, given time constraints). 3 column stack jumps straight to a one column display at 970px, which is pretty extreme.

Where the new logon design goes more in it's own direction as the non-logged in actions (create, reset, lookup) where there isn't a need to have a full width page and there isn't much meaningful navigation (could toss in a sidebar nav with those 3 options + home, but you're generally just in one to be in one) so explanatory text is in a side column.

6, RO typography and form design is not in a usable state IMO. There are repeated consistency and usability issues.
